baseURL = "http://mattabbo.github.io/"
languageCode = "en-us"
title = "Matt Abbo"
theme = "hugo-coder-master"

copyright = ""
publishdir = "mattabbo.github.io"
[Author]
	name = "Matt Aberdein"
[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"
[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"
[params]
	description = "Curious, skeptical optimist."
	twitter = "https://twitter.com/mattabbo"